apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rds-password
  namespace: remni-website
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: rds-password # k8s Secret name
  data:
    - secretKey: POSTGRES_PASSWORD # key in k8s Secret
      remoteRef:
        key: "rds!db-d498bf45-7f6e-469c-a7f4-0cd68d75a82c" # name of the secret in SM
        property: password # extract password field from JSON
