apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rds-password
  namespace: remni-backend
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore    # ← было SecretStore
  target:
    name: rds-password        # имя k8s Secret, который создастся
  data:
    - secretKey: POSTGRES_PASSWORD    # ключ в k8s Secret
      remoteRef:
        key: "rds!db-33b04a53-b4f8-4b17-912a-75112a966a05"   # имя секрета в SM
        property: password             # ← извлечь поле password из JSON
