apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rds-password
  namespace: remni-website
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: rds-password # k8s Secret name
  data:
    - secretKey: POSTGRES_PASSWORD # key in k8s Secret
      remoteRef:
        key: "rds!db-795b5d75-dfdc-481a-b771-db544e2267d4" # name of the secret in SM
        property: password # extract password field from JSON
