apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port | int }}
      protocol: TCP
      targetPort: http
      name: http-backend
  selector:
    app: {{ .Chart.Name }}
