replicaCount: 1

image:
  repository: 474013238842.dkr.ecr.eu-west-2.amazonaws.com/website/backend
  pullPolicy: IfNotPresent
  tag: 131823d69c02ba67dc04e8a7862e810501b4b90c


service:
  type: ClusterIP
  port: 8000

containerPort: 8000

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi

env:
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  POSTGRES_DB: "remni"
  POSTGRES_USER: "postgres"
  POSTGRES_HOST: "db-instance-for-backend.cz2c6sacocxn.eu-west-2.rds.amazonaws.com"
  POSTGRES_PORT: "5432"
  REDIS_URL: "redis://redis:6379/1"

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 20%
